/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.bookify.model.impl;

import com.liferay.bookify.model.Reader;
import com.liferay.bookify.model.ReaderModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Reader service. Represents a row in the &quot;Bookify_Reader&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReaderModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReaderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReaderImpl
 * @generated
 */
@JSON(strict = true)
public class ReaderModelImpl
	extends BaseModelImpl<Reader> implements ReaderModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a reader model instance should use the <code>Reader</code> interface instead.
	 */
	public static final String TABLE_NAME = "Bookify_Reader";

	public static final Object[][] TABLE_COLUMNS = {
		{"readerId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"readerName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("readerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("readerName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Bookify_Reader (readerId LONG not null primary key,groupId LONG,companyId LONG,readerName VARCHAR(75) null,createDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Bookify_Reader";

	public static final String ORDER_BY_JPQL =
		" ORDER BY reader.readerName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Bookify_Reader.readerName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long READERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long READERNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ReaderModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _readerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setReaderId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _readerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Reader.class;
	}

	@Override
	public String getModelClassName() {
		return Reader.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Reader, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Reader, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Reader, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Reader)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Reader, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Reader, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Reader)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Reader, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Reader, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Reader, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Reader, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Reader, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Reader, Object>>();
		Map<String, BiConsumer<Reader, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Reader, ?>>();

		attributeGetterFunctions.put("readerId", Reader::getReaderId);
		attributeSetterBiConsumers.put(
			"readerId", (BiConsumer<Reader, Long>)Reader::setReaderId);
		attributeGetterFunctions.put("groupId", Reader::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Reader, Long>)Reader::setGroupId);
		attributeGetterFunctions.put("companyId", Reader::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Reader, Long>)Reader::setCompanyId);
		attributeGetterFunctions.put("readerName", Reader::getReaderName);
		attributeSetterBiConsumers.put(
			"readerName", (BiConsumer<Reader, String>)Reader::setReaderName);
		attributeGetterFunctions.put("createDate", Reader::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Reader, Date>)Reader::setCreateDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getReaderId() {
		return _readerId;
	}

	@Override
	public void setReaderId(long readerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_readerId = readerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalReaderId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("readerId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public String getReaderName() {
		if (_readerName == null) {
			return "";
		}
		else {
			return _readerName;
		}
	}

	@Override
	public void setReaderName(String readerName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_readerName = readerName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Reader.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Reader toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Reader>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReaderImpl readerImpl = new ReaderImpl();

		readerImpl.setReaderId(getReaderId());
		readerImpl.setGroupId(getGroupId());
		readerImpl.setCompanyId(getCompanyId());
		readerImpl.setReaderName(getReaderName());
		readerImpl.setCreateDate(getCreateDate());

		readerImpl.resetOriginalValues();

		return readerImpl;
	}

	@Override
	public Reader cloneWithOriginalValues() {
		ReaderImpl readerImpl = new ReaderImpl();

		readerImpl.setReaderId(this.<Long>getColumnOriginalValue("readerId"));
		readerImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		readerImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		readerImpl.setReaderName(
			this.<String>getColumnOriginalValue("readerName"));
		readerImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));

		return readerImpl;
	}

	@Override
	public int compareTo(Reader reader) {
		int value = 0;

		value = getReaderName().compareTo(reader.getReaderName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Reader)) {
			return false;
		}

		Reader reader = (Reader)object;

		long primaryKey = reader.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Reader> toCacheModel() {
		ReaderCacheModel readerCacheModel = new ReaderCacheModel();

		readerCacheModel.readerId = getReaderId();

		readerCacheModel.groupId = getGroupId();

		readerCacheModel.companyId = getCompanyId();

		readerCacheModel.readerName = getReaderName();

		String readerName = readerCacheModel.readerName;

		if ((readerName != null) && (readerName.length() == 0)) {
			readerCacheModel.readerName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			readerCacheModel.createDate = createDate.getTime();
		}
		else {
			readerCacheModel.createDate = Long.MIN_VALUE;
		}

		return readerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Reader, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Reader, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Reader, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Reader)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Reader>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Reader.class, ModelWrapper.class);

	}

	private long _readerId;
	private long _groupId;
	private long _companyId;
	private String _readerName;
	private Date _createDate;

	public <T> T getColumnValue(String columnName) {
		Function<Reader, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Reader)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("readerId", _readerId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("readerName", _readerName);
		_columnOriginalValues.put("createDate", _createDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("readerId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("readerName", 8L);

		columnBitmasks.put("createDate", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Reader _escapedModel;

}