/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.bookify.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Book service. Represents a row in the &quot;Bookify_Book&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.bookify.model.impl.BookModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.bookify.model.impl.BookImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Book
 * @generated
 */
@ProviderType
public interface BookModel extends BaseModel<Book>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a book model instance should use the {@link Book} interface instead.
	 */

	/**
	 * Returns the primary key of this book.
	 *
	 * @return the primary key of this book
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this book.
	 *
	 * @param primaryKey the primary key of this book
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the book ID of this book.
	 *
	 * @return the book ID of this book
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this book.
	 *
	 * @param bookId the book ID of this book
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the group ID of this book.
	 *
	 * @return the group ID of this book
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this book.
	 *
	 * @param groupId the group ID of this book
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this book.
	 *
	 * @return the company ID of this book
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this book.
	 *
	 * @param companyId the company ID of this book
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the reader name of this book.
	 *
	 * @return the reader name of this book
	 */
	@AutoEscape
	public String getReaderName();

	/**
	 * Sets the reader name of this book.
	 *
	 * @param readerName the reader name of this book
	 */
	public void setReaderName(String readerName);

	/**
	 * Returns the create date of this book.
	 *
	 * @return the create date of this book
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this book.
	 *
	 * @param createDate the create date of this book
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this book.
	 *
	 * @return the modified date of this book
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this book.
	 *
	 * @param modifiedDate the modified date of this book
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the book name of this book.
	 *
	 * @return the book name of this book
	 */
	@AutoEscape
	public String getBookName();

	/**
	 * Sets the book name of this book.
	 *
	 * @param bookName the book name of this book
	 */
	public void setBookName(String bookName);

	/**
	 * Returns the book author of this book.
	 *
	 * @return the book author of this book
	 */
	@AutoEscape
	public String getBookAuthor();

	/**
	 * Sets the book author of this book.
	 *
	 * @param bookAuthor the book author of this book
	 */
	public void setBookAuthor(String bookAuthor);

	/**
	 * Returns the book publication date of this book.
	 *
	 * @return the book publication date of this book
	 */
	public Date getBookPublicationDate();

	/**
	 * Sets the book publication date of this book.
	 *
	 * @param bookPublicationDate the book publication date of this book
	 */
	public void setBookPublicationDate(Date bookPublicationDate);

	/**
	 * Returns the reader ID of this book.
	 *
	 * @return the reader ID of this book
	 */
	public long getReaderId();

	/**
	 * Sets the reader ID of this book.
	 *
	 * @param readerId the reader ID of this book
	 */
	public void setReaderId(long readerId);

	@Override
	public Book cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}