/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.bookify.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Reader service. Represents a row in the &quot;Bookify_Reader&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.bookify.model.impl.ReaderModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.bookify.model.impl.ReaderImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Reader
 * @generated
 */
@ProviderType
public interface ReaderModel extends BaseModel<Reader>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reader model instance should use the {@link Reader} interface instead.
	 */

	/**
	 * Returns the primary key of this reader.
	 *
	 * @return the primary key of this reader
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reader.
	 *
	 * @param primaryKey the primary key of this reader
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the reader ID of this reader.
	 *
	 * @return the reader ID of this reader
	 */
	public long getReaderId();

	/**
	 * Sets the reader ID of this reader.
	 *
	 * @param readerId the reader ID of this reader
	 */
	public void setReaderId(long readerId);

	/**
	 * Returns the group ID of this reader.
	 *
	 * @return the group ID of this reader
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this reader.
	 *
	 * @param groupId the group ID of this reader
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this reader.
	 *
	 * @return the company ID of this reader
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this reader.
	 *
	 * @param companyId the company ID of this reader
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the reader name of this reader.
	 *
	 * @return the reader name of this reader
	 */
	@AutoEscape
	public String getReaderName();

	/**
	 * Sets the reader name of this reader.
	 *
	 * @param readerName the reader name of this reader
	 */
	public void setReaderName(String readerName);

	/**
	 * Returns the create date of this reader.
	 *
	 * @return the create date of this reader
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this reader.
	 *
	 * @param createDate the create date of this reader
	 */
	public void setCreateDate(Date createDate);

	@Override
	public Reader cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}